## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
columns = application_df.columns
print(columns)

Index(['EIN', 'NAME', 'APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION',
       'USE_CASE', 'ORGANIZATION', 'STATUS', 'INCOME_AMT',
       'SPECIAL_CONSIDERATIONS', 'ASK_AMT', 'IS_SUCCESSFUL'],
      dtype='object')

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.

application_df.drop(['EIN', 'NAME'], axis=1, inplace=True)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Determine the number of unique values in each column.
unique_values = application_df.nunique()
unique_values

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
value_counts_application_type = application_df['APPLICATION_TYPE'].value_counts()
print(value_counts_application_type)

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# Cutoff value will be set to 500
# use the variable name `application_types_to_replace`
cutoff_value = 500
application_types_to_replace = list(value_counts_application_type[value_counts_application_type < cutoff_value].index)

# print the list of application types to replace
print(application_types_to_replace)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
value_counts_classification = application_df['CLASSIFICATION'].value_counts()
print(value_counts_classification)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
value_counts_classification1 = value_counts_classification[value_counts_classification > 1]
print(value_counts_classification1)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_value_classifications = 1000
classifications_to_replace = list(value_counts_classification[value_counts_classification < cutoff_value_classifications].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [ ]:
# Review the info
application_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   APPLICATION_TYPE        34299 non-null  object
 1   AFFILIATION             34299 non-null  object
 2   CLASSIFICATION          34299 non-null  object
 3   USE_CASE                34299 non-null  object
 4   ORGANIZATION            34299 non-null  object
 5   STATUS                  34299 non-null  int64
 6   INCOME_AMT              34299 non-null  object
 7   SPECIAL_CONSIDERATIONS  34299 non-null  object
 8   ASK_AMT                 34299 non-null  int64
 9   IS_SUCCESSFUL           34299 non-null  int64
dtypes: int64(3), object(7)
memory usage: 2.6+ MB

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df_dummies = pd.get_dummies(application_df, columns=[
    'APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE',
    'ORGANIZATION', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS'
])
# Display the transformed data
application_df_dummies

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
34295,1,5000,0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
34296,1,5000,0,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34297,1,5000,1,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
34298,1,36500179,0,False,False,False,True,False,False,False,...,False,False,False,False,True,False,False,False,True,False

In [ ]:
# Split our preprocessed data into our features and target arrays
y = application_df_dummies.IS_SUCCESSFUL.values
X = application_df_dummies.drop(columns="IS_SUCCESSFUL").values

# Split the preprocessed data into a training and testing dataset
X_train,X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
# number_of_features is the number of input features
number_of_features = X_train_scaled.shape[1]

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=80, activation='relu', input_dim=number_of_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                3520

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 5981 (23.36 KB)
Trainable params: 5981 (23.36 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer='adam', metrics=["accuracy"])

In [ ]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.5691 - accuracy: 0.7226
Epoch 2/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5568 - accuracy: 0.7303
Epoch 3/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5525 - accuracy: 0.7319
Epoch 4/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5509 - accuracy: 0.7327
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7341
Epoch 6/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5482 - accuracy: 0.7338
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5475 - accuracy: 0.7344
Epoch 8/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7345
Epoch 9/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7350
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5452 - accuracy: 0.7354
Epoch 11/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5450 - accuracy: 0.7360
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5445 - accuracy: 0.7358
Epoch 13/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7372
Epoch 14/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7367
Epoch 15/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7370
Epoch 16/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7367
Epoch 17/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7372
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7388
Epoch 19/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5425 - accuracy: 0.7373
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5417 - accuracy: 0.7382
Epoch 21/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7390
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7386
Epoch 23/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7383
Epoch 24/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7385
Epoch 25/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7382
Epoch 26/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7385
Epoch 27/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5405 - accuracy: 0.7376
Epoch 28/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5403 - accuracy: 0.7390
Epoch 29/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7382
Epoch 30/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7389
Epoch 31/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7390
Epoch 32/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7393
Epoch 33/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7400
Epoch 34/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7393
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7392
Epoch 36/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5389 - accuracy: 0.7389
Epoch 37/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5387 - accuracy: 0.7389
Epoch 38/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7385
Epoch 39/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5386 - accuracy: 0.7395
Epoch 40/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5387 - accuracy: 0.7402
Epoch 41/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5381 - accuracy: 0.7388
Epoch 42/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5377 - accuracy: 0.7419
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7390
Epoch 44/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5382 - accuracy: 0.7390
Epoch 45/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5381 - accuracy: 0.7396
Epoch 46/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5381 - accuracy: 0.7402
Epoch 47/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5379 - accuracy: 0.7401
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7396
Epoch 49/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5372 - accuracy: 0.7397
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5375 - accuracy: 0.7407
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7392
Epoch 52/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5370 - accuracy: 0.7405
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7400
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7407
Epoch 55/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5369 - accuracy: 0.7406
Epoch 56/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5370 - accuracy: 0.7402
Epoch 57/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7398
Epoch 58/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7401
Epoch 59/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5366 - accuracy: 0.7407
Epoch 60/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5364 - accuracy: 0.7406
Epoch 61/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5363 - accuracy: 0.7402
Epoch 62/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5362 - accuracy: 0.7392
Epoch 63/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7408
Epoch 64/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5364 - accuracy: 0.7414
Epoch 65/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7408
Epoch 66/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5364 - accuracy: 0.7410
Epoch 67/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5358 - accuracy: 0.7394
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5360 - accuracy: 0.7400
Epoch 69/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5359 - accuracy: 0.7414
Epoch 70/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5359 - accuracy: 0.7400
Epoch 71/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5358 - accuracy: 0.7407
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7407
Epoch 73/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5355 - accuracy: 0.7410
Epoch 74/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5354 - accuracy: 0.7415
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5352 - accuracy: 0.7407
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7403
Epoch 77/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5356 - accuracy: 0.7411
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5354 - accuracy: 0.7397
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5354 - accuracy: 0.7402
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5354 - accuracy: 0.7409
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7407
Epoch 82/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7413
Epoch 83/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5354 - accuracy: 0.7398
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5354 - accuracy: 0.7410
Epoch 85/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5345 - accuracy: 0.7410
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5349 - accuracy: 0.7408
Epoch 87/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5349 - accuracy: 0.7407
Epoch 88/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7411
Epoch 89/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5350 - accuracy: 0.7411
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7406
Epoch 91/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7404
Epoch 92/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7397
Epoch 93/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5351 - accuracy: 0.7413
Epoch 94/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5344 - accuracy: 0.7415
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7414
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7409
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7412
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7412
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5342 - accuracy: 0.7416
Epoch 100/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7411

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5620 - accuracy: 0.7251 - 607ms/epoch - 2ms/step
Loss: 0.5620238780975342, Accuracy: 0.7251312136650085

In [ ]:
# Export our model to HDF5 file

import os
from keras.models import Sequential

#  renaming the model for better understanding
model = nn

# Defining the path for saving the file
output_dir = '/content/Output'

# Creating the directory if it doesn't exist
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# Saving the model to an HDF5 file
model.save(os.path.join(output_dir, 'AlphabetSoupCharity.h5'))

In [ ]:
# saving the file locally

from google.colab import files
files.download(os.path.join(output_dir, 'AlphabetSoupCharity.h5'))

In [ ]:
# Create a method that creates a new Sequential model with hyperparameter options
def create_model(hp):
    nn_model = tf.keras.models.Sequential()

    # Allow kerastuner to decide which activation function to use in hidden layers
    activation = hp.Choice('activation',['relu','tanh','sigmoid'])

    # Allow kerastuner to decide number of neurons in first layer
    nn_model.add(tf.keras.layers.Dense(units=hp.Int('first_units',
        min_value=1,
        max_value=10,
        step=2), activation=activation, input_dim=number_of_features))

    # Allow kerastuner to decide number of hidden layers and neurons in hidden layers
    for i in range(hp.Int('num_layers', 1, 6)):
        nn_model.add(tf.keras.layers.Dense(units=hp.Int('units_' + str(i),
            min_value=1,
            max_value=10,
            step=2),
            activation=activation))

    nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

    # Compile the model
    nn_model.compile(loss="binary_crossentropy", optimizer='adam', metrics=["accuracy"])

    return nn_model

In [ ]:
!pip install keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.7-py3-none-any.whl (129 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.1/129.1 kB 2.8 MB/s eta 0:00:00
Requirement already satisfied: keras in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (2.15.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (24.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (2.31.0)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (2024.6.2)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.7 kt-legacy-1.0.5

In [ ]:
# Import the kerastuner library
import keras_tuner as kt

tuner = kt.Hyperband(
    create_model,
    objective="val_accuracy",
    max_epochs=20,
    hyperband_iterations=2)

In [ ]:
# Run the kerastuner search for best hyperparameters
tuner.search(X_train_scaled,y_train,epochs=20,validation_data=(X_test_scaled,y_test))

Trial 60 Complete [00h 00m 57s]
val_accuracy: 0.7258309125900269

Best val_accuracy So Far: 0.7272303104400635
Total elapsed time: 00h 25m 11s

In [ ]:
# Get best model hyperparameters
best_hyper = tuner.get_best_hyperparameters(1)[0]
best_hyper.values

{'activation': 'tanh',
 'first_units': 5,
 'num_layers': 5,
 'units_0': 5,
 'units_1': 9,
 'units_2': 1,
 'units_3': 3,
 'units_4': 5,
 'units_5': 9,
 'tuner/epochs': 7,
 'tuner/initial_epoch': 0,
 'tuner/bracket': 1,
 'tuner/round': 0}

In [ ]:
# Evaluate best model against full test data
best_model = tuner.get_best_models(1)[0]
model_loss, model_accuracy = best_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5596 - accuracy: 0.7272 - 1s/epoch - 5ms/step
Loss: 0.559550404548645, Accuracy: 0.7272303104400635